import { TerrainType, type TerrainMap } from './MapTypes';

const G = TerrainType.Grass;
const D = TerrainType.Dirt;

// 40 x 23 cells at 32px per tile fills a 1280 x 720 design view.
const MAP_ROWS = [
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    'GGGGGGGGGDDDDDDDDDDGGGGGGGGGGGGGGGGGGGGG',
    'GGGGGGGGDDDDDDDDDDDDGGGGGGGGGGGGGGGGGGGG',
    'GGGGGGGDDDDDDDDDDDDDDGGGGGGGGGGGGGGGGGGG',
    'GGGGGGGDDDDDDDDDDDDDDGGGGGGGGGGGGGGGGGGG',
    'GGGGGGGDDDDDDDDDDDDDDGGGGGDDDDDDDDGGGGGG',
    'GGGGGGGGDDDDDDDDDDDDGGGGGDDDDDDDDDDGGGGG',
    'GGGGGGGGGDDDDDDDDDDGGGGGDDDDDDDDDDDDGGGG',
    'GGGGGGGGGGGGDDDDGGGGGGGDDDDDDDDDDDDGGGGG',
    'GGGGGGGGGGGDDDDDDGGGGGDDDDDDDDDDDDDDGGGG',
    'GGGGGGGGGGDDDDDDDDGGGGDDDDDDDDDDDDDDGGGG',
    'GGGGGGGGGGDDDDDDDDGGGGGDDDDDDDDDDDDGGGGG',
    'GGGGGGGGGGGDDDDDDGGGGGGDDDDDDDDDDDDGGGGG',
    'GGGGGGGGGGGGDDDDGGGGGGGGDDDDDDDDDDGGGGGG',
    'GGGGGGGGGGGGGGGGGGGGGGGGGDDDDDDDDGGGGGGG',
    'GGGGGGGGGGGGGGGGGGGGGGGGGGDDDDDDGGGGGGGG',
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGDDDDGGGGGGGGG',
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
];

export const STATIC_MAP: TerrainMap = MAP_ROWS.map((row) =>
    Array.from(row, (cell) => (cell === 'D' ? D : G)),
);
